### ISSUE TITLE
更新后openai用不了（Openai doesn't work after update）

### ISSUE THREAD

**Issue by paolaoshi** [MinusZoneAI/ComfyUI-Prompt-MZ#13]
Error occurred when executing MZ_OpenAIApiCLIPTextEncode:

No module named 'mz_openaiapi'
![QQ截图20240602133955](https://github.com/MinusZoneAI/ComfyUI-Prompt-MZ/assets/130342241/aafa6b40-3183-4264-98c3-ce94178e978c)

**Comment by wailovet** [comment]
更新后再试试看

**Comment by upboy-web** [comment]
6月2好，下午2点多更新后，还是不行……
![01](https://github.com/MinusZoneAI/ComfyUI-Prompt-MZ/assets/130342241/979d08f8-e361-4b7b-a5e4-603228d40d8a)

**Comment by paolaoshi** [comment]
更新后可以用了，已解决……
