### ISSUE TITLE
好像每次运行都会重新加载模型

### ISSUE THREAD

**Issue by lzhfdwu007** [MinusZoneAI/ComfyUI-Prompt-MZ#4]
能不能设置一个模型常驻的的开关？或者手动加载卸载的开关？

**Comment by wailovet** [comment]
> 能不能设置一个模型常驻的的开关？或者手动加载卸载的开关？

会加的

**Comment by lzhfdwu007** [comment]
作者 我可以加你QQ骚扰你妈？
&nbsp;


eis
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月25日(星期四) 凌晨0:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MinusZoneAI/ComfyUI-Prompt-MZ] 好像每次运行都会重新加载模型 (Issue #4)














  
能不能设置一个模型常驻的的开关？或者手动加载卸载的开关？
  
会的,等我加了这里喊你

**Comment by wailovet** [comment]
> 作者 我可以加你QQ骚扰你妈？ &nbsp; eis ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年4月25日(星期四) 凌晨0:58 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [MinusZoneAI/ComfyUI-Prompt-MZ] 好像每次运行都会重新加载模型 (Issue #4) 能不能设置一个模型常驻的的开关？或者手动加载卸载的开关？ 会的,等我加了这里喊你 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

加我微信呗 微信号:minrszone

**Comment by wailovet** [comment]
![image](https://github.com/MinusZoneAI/ComfyUI-Prompt-MZ/assets/5035199/61be0e66-d98a-4086-b96a-8a242144fd7c)
