### ISSUE TITLE
ComfyUI-Prompt-MZ/mz_llama3.py", line 93, in query_beautify_prompt_text     if response["description"] != "": KeyError: 'description'

### ISSUE THREAD

**Issue by arixlin** [MinusZoneAI/ComfyUI-Prompt-MZ#6]

**Comment by wailovet** [comment]
Does this happen occasionally or every time?

**Comment by cardenluo** [comment]
![image](https://github.com/MinusZoneAI/ComfyUI-Prompt-MZ/assets/133877069/bb0724b8-efa0-4896-8457-a41f9a97f765)
me  too , it does not work .

**Comment by wailovet** [comment]
Will the error still occur if you try again after updating?

**Comment by arixlin** [comment]
@wailovet  回退了好几个版本 还是会发生，
最新版本错误
```

2024-04-28 11:40:48,632- root:450- INFO- got prompt
2024-04-28 11:40:48,635- root:667- ERROR- Failed to validate prompt for output 6:
2024-04-28 11:40:48,635- root:687- ERROR- * MZ_LLama3CLIPTextEncode 4:
2024-04-28 11:40:48,635- root:689- ERROR-   - Required input is missing: prompt_version
2024-04-28 11:40:48,635- root:689- ERROR-   - Required input is missing: keep_device
2024-04-28 11:40:48,635- root:691- ERROR- Output will be ignored
2024-04-28 11:40:48,635- root:482- WARNING- invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
```

**Comment by wailovet** [comment]
> @wailovet 回退了好几个版本 还是会发生， 最新版本错误
> 
> ```
> 
> 2024-04-28 11:40:48,632- root:450- INFO- got prompt
> 2024-04-28 11:40:48,635- root:667- ERROR- Failed to validate prompt for output 6:
> 2024-04-28 11:40:48,635- root:687- ERROR- * MZ_LLama3CLIPTextEncode 4:
> 2024-04-28 11:40:48,635- root:689- ERROR-   - Required input is missing: prompt_version
> 2024-04-28 11:40:48,635- root:689- ERROR-   - Required input is missing: keep_device
> 2024-04-28 11:40:48,635- root:691- ERROR- Output will be ignored
> 2024-04-28 11:40:48,635- root:482- WARNING- invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
> ```

最新的节点的输入有修改,你需要删除一下然后重新创建下节点

**Comment by arixlin** [comment]
> > @wailovet 回退了好几个版本 还是会发生， 最新版本错误
> > ```
> > 
> > 2024-04-28 11:40:48,632- root:450- INFO- got prompt
> > 2024-04-28 11:40:48,635- root:667- ERROR- Failed to validate prompt for output 6:
> > 2024-04-28 11:40:48,635- root:687- ERROR- * MZ_LLama3CLIPTextEncode 4:
> > 2024-04-28 11:40:48,635- root:689- ERROR-   - Required input is missing: prompt_version
> > 2024-04-28 11:40:48,635- root:689- ERROR-   - Required input is missing: keep_device
> > 2024-04-28 11:40:48,635- root:691- ERROR- Output will be ignored
> > 2024-04-28 11:40:48,635- root:482- WARNING- invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
> > ```
> 
> 最新的节点的输入有修改,你需要删除一下然后重新创建下节点

有的新的报错
`
AttributeError: module 'llama_cpp' has no attribute 'LLAMA_SPLIT_MODE_LAYER'
`
工程的的llama_cpp需要哪个版本

**Comment by wailovet** [comment]
> > > @wailovet 回退了好几个版本 还是会发生， 最新版本错误
> > > ```
> > > 
> > > 2024-04-28 11:40:48,632- root:450- INFO- got prompt
> > > 2024-04-28 11:40:48,635- root:667- ERROR- Failed to validate prompt for output 6:
> > > 2024-04-28 11:40:48,635- root:687- ERROR- * MZ_LLama3CLIPTextEncode 4:
> > > 2024-04-28 11:40:48,635- root:689- ERROR-   - Required input is missing: prompt_version
> > > 2024-04-28 11:40:48,635- root:689- ERROR-   - Required input is missing: keep_device
> > > 2024-04-28 11:40:48,635- root:691- ERROR- Output will be ignored
> > > 2024-04-28 11:40:48,635- root:482- WARNING- invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
> > > ```
> > 
> > 
> > 最新的节点的输入有修改,你需要删除一下然后重新创建下节点
> 
> 有的新的报错 `AttributeError: module 'llama_cpp' has no attribute 'LLAMA_SPLIT_MODE_LAYER'` 工程的的llama_cpp需要哪个版本

目前用的是 0.2.63
