### ISSUE TITLE
大佬，能否增加支持第三方openai api的功能

### ISSUE THREAD

**Issue by msola-ht** [MinusZoneAI/ComfyUI-Prompt-MZ#7]
试了很多个提示词润色，您这个效果是最好的
但是用llama 大概一次要30秒到1分钟能否增加支持openai api 的形式
这样可以使用更多模型
也减少本地压力

**Comment by wailovet** [comment]
我openai几个账号全挂了,你可以加一下我微信搞个key借我调试

**Comment by msola-ht** [comment]
> 我openai几个账号全挂了,你可以加一下我微信搞个key借我调试

我没有官方的api用的是中转的，如果有需要可以给你调试

**Comment by wailovet** [comment]
已新增OpenAIApi节点
